---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: postgresql
    image: ${MOLECULE_IMAGE}
    command: /sbin/init
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      roles_path: "$HOME/.ansible/roles/:/tmp"
  connection_options:
    postgresql_service_name: postgresql-14
  env:
    ANSIBLE_REMOTE_TEMP: /tmp/.ansible/tmp
    ANSIBLE_LOCAL_TEMP: /tmp/.ansible/tmp
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
