---
- name: Verify
  hosts: all
  become: true

  vars:
    postgresql_version: "16"
    expected_service: "postgresql-{{ postgresql_version }}"
    postgresql_service_name: "postgresql-{{ postgresql_version }}"

  tasks:
    - name: Check if PostgreSQL client is installed
      ansible.builtin.command: psql --version
      register: psql_version
      changed_when: false

    - name: Collect service facts
      ansible.builtin.service_facts:

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Assert service is running
      ansible.builtin.assert:
        that:
          - (expected_service ~ '.service') in ansible_facts.services
          - ansible_facts.services[expected_service ~ '.service'].state == 'running'

    - name: Show PostgreSQL version
      ansible.builtin.debug:
        var: psql_version

    - name: Show postgresql service status
      ansible.builtin.debug:
        var: ansible_facts.services[postgresql_service_name + '.service']

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
