---
- name: Install PostgreSQL RPM
  ansible.builtin.dnf:
    name: "{{ posgtresql_rpm }}"
    disable_gpg_check: yes

- name: Disable Repo GPG check of PostgreSQL repo
  ansible.builtin.replace:
    path: /etc/yum.repos.d/pgdg-redhat-all.repo
    regexp: 'repo_gpgcheck = 1'
    replace: 'repo_gpgcheck = 0'

- name: Disable default PostgreSQL module
  ansible.builtin.command: dnf -qy --nogpgcheck module disable postgresql
  changed_when: false

- name: Install PostgreSQL
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  loop: "{{ postgresql_packages }}"
