---
- name: Install PostgreSQL RPM
  ansible.builtin.yum:
    name: "{{ posgtresql_rpm }}"
    disable_gpg_check: yes

- name: Install PostgreSQL
  ansible.builtin.dnf:
    name: "{{ item }}"
    enablerepo: "{{ postgresql_repo }}"
    state: present
  loop: "{{ postgresql_packages }}"
