---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: postgresql
    image: ${MOLECULE_IMAGE}
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      roles_path: "$HOME/.ansible/roles/:/tmp"
  connection_options:
    postgresql_init_cmd: '/usr/pgsql-13/bin/postgresql-13-setup initdb'
    postgresql_init_cmd_options: '--encoding=UTF-8 --no-locale'
    postgresql_packages:
      - postgresql13-devel
      - postgresql13-server
    postgresql_service_name: postgresql-13
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
